spring.datasource.url=jdbc:postgresql://db:5432/bappoint_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


stripe.secret.key=${STRIPE_SECRET_KEY}

stripe.webhook.secret=${STRIPE_KEY_TEMPORARILY}

clerk.secret-key=${CLERK_SECRET_KEY}

clerk.jwks.url=https://localhost:3000.clerk.accounts.dev/.well-known/jwks.json